const webtoons = [
  {
    id: 1,
    ranking: 1,
    rankingStatus: 'stable',
    rankingChanged: 0,
    title: '연애혁명',
    author: '232',
    score: 9.89,
    scoreChangedStatus: 'up',
    scoreChangedPercent: 1.54,
  },
  {
    id: 2,
    ranking: 2,
    rankingStatus: 'up',
    rankingChanged: 3,
    title: '흑막 여주가 날 새엄마로 만들려고 해',
    author: '자까',
    score: 9.89,
    scoreChangedStatus: 'up',
    scoreChangedPercent: 1.54,
  },
  {
    id: 3,
    ranking: 3,
    rankingStatus: 'down',
    rankingChanged: 1,
    title: '먹는 인생',
    author: '홍끼',
    score: 9.89,
    scoreChangedStatus: 'down',
    scoreChangedPercent: 1.54,
  },
  {
    id: 4,
    ranking: 1,
    rankingStatus: 'stable',
    rankingChanged: 0,
    title: '연애혁명',
    author: '232',
    score: 9.89,
    scoreChangedStatus: 'up',
    scoreChangedPercent: 1.54,
  },
  {
    id: 5,
    ranking: 2,
    rankingStatus: 'up',
    rankingChanged: 3,
    title: '흑막 여주가 날 새엄마로 만들려고 해',
    author: '자까',
    score: 9.89,
    scoreChangedStatus: 'up',
    scoreChangedPercent: 1.54,
  },
  {
    id: 6,
    ranking: 3,
    rankingStatus: 'down',
    rankingChanged: 1,
    title: '먹는 인생',
    author: '홍끼',
    score: 9.89,
    scoreChangedStatus: 'down',
    scoreChangedPercent: 1.54,
  },
  {
    id: 7,
    ranking: 1,
    rankingStatus: 'stable',
    rankingChanged: 0,
    title: '연애혁명',
    author: '232',
    score: 9.89,
    scoreChangedStatus: 'up',
    scoreChangedPercent: 1.54,
  },
  {
    id: 8,
    ranking: 2,
    rankingStatus: 'up',
    rankingChanged: 3,
    title: '흑막 여주가 날 새엄마로 만들려고 해',
    author: '자까',
    score: 9.89,
    scoreChangedStatus: 'up',
    scoreChangedPercent: 1.54,
  },
  {
    id: 9,
    ranking: 3,
    rankingStatus: 'down',
    rankingChanged: 1,
    title: '먹는 인생',
    author: '홍끼',
    score: 9.89,
    scoreChangedStatus: 'down',
    scoreChangedPercent: 1.54,
  },
  {
    id: 10,
    ranking: 1,
    rankingStatus: 'stable',
    rankingChanged: 0,
    title: '연애혁명',
    author: '232',
    score: 9.89,
    scoreChangedStatus: 'up',
    scoreChangedPercent: 1.54,
  },
  {
    id: 11,
    ranking: 2,
    rankingStatus: 'up',
    rankingChanged: 3,
    title: '흑막 여주가 날 새엄마로 만들려고 해',
    author: '자까',
    score: 9.89,
    scoreChangedStatus: 'up',
    scoreChangedPercent: 1.54,
  },
  {
    id: 12,
    ranking: 3,
    rankingStatus: 'down',
    rankingChanged: 1,
    title: '먹는 인생',
    author: '홍끼',
    score: 9.89,
    scoreChangedStatus: 'down',
    scoreChangedPercent: 1.54,
  },
];

export { webtoons };
