type Status = 'up' | 'down' | 'stable';

interface Webtoon {
  id: number;
  ranking: number;
  rankingStatus: Status;
  rankingChanged: number;
  title: string;
  author: string;
  imageUrl: string;
  score: number;
  scoreChangedStatus: Status;
  scoreChangedPercent: number;
}

const webtoons: Webtoon[] = [
  {
    id: 1,
    ranking: 1,
    rankingStatus: 'stable',
    rankingChanged: 0,
    title: '연애혁명',
    author: '232',
    imageUrl: '/images/thumb_연애혁명.png',
    score: 9.99,
    scoreChangedStatus: 'stable',
    scoreChangedPercent: 0.0,
  },
  {
    id: 2,
    ranking: 2,
    rankingStatus: 'up',
    rankingChanged: 3,
    title: '흑막 여주가 날 새엄마로 만들려고 해',
    author: '자까',
    imageUrl: '/images/thumb_세기말_풋사과_보습학원.png',
    score: 9.89,
    scoreChangedStatus: 'up',
    scoreChangedPercent: 1.54,
  },
  {
    id: 3,
    ranking: 3,
    rankingStatus: 'down',
    rankingChanged: 1,
    title: '먹는 인생',
    author: '홍끼',
    imageUrl: '/images/thumbnail_먹는인생.jpeg',
    score: 9.89,
    scoreChangedStatus: 'down',
    scoreChangedPercent: 1.54,
  },
  {
    id: 4,
    ranking: 1,
    rankingStatus: 'stable',
    rankingChanged: 0,
    title: '연애혁명',
    author: '232',
    imageUrl: '/images/thumb_연애혁명.png',
    score: 9.89,
    scoreChangedStatus: 'up',
    scoreChangedPercent: 1.54,
  },
  {
    id: 5,
    ranking: 2,
    rankingStatus: 'up',
    rankingChanged: 3,
    title: '흑막 여주가 날 새엄마로 만들려고 해',
    author: '자까',
    imageUrl: '/images/thumb_세기말_풋사과_보습학원.png',
    score: 9.89,
    scoreChangedStatus: 'up',
    scoreChangedPercent: 1.54,
  },
  {
    id: 6,
    ranking: 3,
    rankingStatus: 'down',
    rankingChanged: 1,
    title: '먹는 인생',
    author: '홍끼',
    imageUrl: '/images/thumb_먹는인생.png',
    score: 9.89,
    scoreChangedStatus: 'down',
    scoreChangedPercent: 1.54,
  },
  {
    id: 7,
    ranking: 1,
    rankingStatus: 'stable',
    rankingChanged: 0,
    title: '연애혁명',
    author: '232',
    imageUrl: '/images/thumb_연애혁명.png',
    score: 9.89,
    scoreChangedStatus: 'up',
    scoreChangedPercent: 1.54,
  },
  {
    id: 8,
    ranking: 2,
    rankingStatus: 'up',
    rankingChanged: 3,
    title: '흑막 여주가 날 새엄마로 만들려고 해',
    author: '자까',
    imageUrl: '/images/thumb_세기말_풋사과_보습학원.png',
    score: 9.89,
    scoreChangedStatus: 'up',
    scoreChangedPercent: 1.54,
  },
  {
    id: 9,
    ranking: 3,
    rankingStatus: 'down',
    rankingChanged: 1,
    title: '먹는 인생',
    author: '홍끼',
    imageUrl: '/images/thumb_먹는인생.png',
    score: 9.89,
    scoreChangedStatus: 'down',
    scoreChangedPercent: 1.54,
  },
  {
    id: 10,
    ranking: 1,
    rankingStatus: 'stable',
    rankingChanged: 0,
    title: '연애혁명',
    author: '232',
    imageUrl: '/images/thumb_연애혁명.png',
    score: 9.89,
    scoreChangedStatus: 'up',
    scoreChangedPercent: 1.54,
  },
  {
    id: 11,
    ranking: 2,
    rankingStatus: 'up',
    rankingChanged: 3,
    title: '흑막 여주가 날 새엄마로 만들려고 해',
    author: '자까',
    imageUrl: '/images/thumb_세기말_풋사과_보습학원.png',
    score: 9.89,
    scoreChangedStatus: 'up',
    scoreChangedPercent: 1.54,
  },
  {
    id: 12,
    ranking: 3,
    rankingStatus: 'down',
    rankingChanged: 1,
    title: '먹는 인생',
    author: '홍끼',
    imageUrl: '/images/thumb_먹는인생.png',
    score: 9.89,
    scoreChangedStatus: 'down',
    scoreChangedPercent: 1.54,
  },
];

export { webtoons };
